name: Publish to PyPI with OIDC



on:

  push:

    tags:

      - "v*.*.*"



permissions:

  id-token: write  # OIDC erforderlich

  contents: read



jobs:

  publish:

    uses: pypa/gh-action-pypi-publish@v1.9.0

    with:

      password: ""  # Nicht benutzen â€“ bei OIDC leer lassen!

    secrets: inherit

    environment: pypi
